/**
 * High-fidelity NBA Game Data
 * Static dataset for instant rendering (no external API dependencies)
 */

const GAME_DATA = {
    home: {
        name: 'Los Angeles Lakers',
        record: '22-8',
        players: [
            {
                name: 'LeBron James',
                position: 'SF',
                points: 28,
                rebounds: 9,
                assists: 7,
                fgm: 11,
                fga: 22,
            },
            {
                name: 'Anthony Davis',
                position: 'PF',
                points: 24,
                rebounds: 12,
                assists: 2,
                fgm: 10,
                fga: 19,
            },
            {
                name: 'Austin Reaves',
                position: 'SG',
                points: 18,
                rebounds: 3,
                assists: 5,
                fgm: 7,
                fga: 16,
            },
            {
                name: 'D\'Angelo Russell',
                position: 'PG',
                points: 16,
                rebounds: 2,
                assists: 8,
                fgm: 6,
                fga: 14,
            },
            {
                name: 'Rui Hachimura',
                position: 'PF',
                points: 12,
                rebounds: 5,
                assists: 1,
                fgm: 5,
                fga: 11,
            },
            {
                name: 'Christian Wood',
                position: 'C',
                points: 8,
                rebounds: 6,
                assists: 1,
                fgm: 3,
                fga: 8,
            },
            {
                name: 'Spencer Dinwiddie',
                position: 'PG',
                points: 6,
                rebounds: 1,
                assists: 2,
                fgm: 2,
                fga: 6,
            },
            {
                name: 'Jalen Hood-Schifino',
                position: 'PG',
                points: 6,
                rebounds: 2,
                assists: 1,
                fgm: 2,
                fga: 5,
            },
        ],
    },
    away: {
        name: 'Boston Celtics',
        record: '24-6',
        players: [
            {
                name: 'Jayson Tatum',
                position: 'SF',
                points: 32,
                rebounds: 10,
                assists: 5,
                fgm: 13,
                fga: 25,
            },
            {
                name: 'Jaylen Brown',
                position: 'SF',
                points: 26,
                rebounds: 8,
                assists: 3,
                fgm: 10,
                fga: 21,
            },
            {
                name: 'Derrick White',
                position: 'SG',
                points: 18,
                rebounds: 4,
                assists: 6,
                fgm: 7,
                fga: 14,
            },
            {
                name: 'Al Horford',
                position: 'C',
                points: 14,
                rebounds: 7,
                assists: 2,
                fgm: 5,
                fga: 11,
            },
            {
                name: 'Sam Hauser',
                position: 'PF',
                points: 12,
                rebounds: 3,
                assists: 1,
                fgm: 4,
                fga: 9,
            },
            {
                name: 'Luke Kornet',
                position: 'C',
                points: 10,
                rebounds: 5,
                assists: 1,
                fgm: 4,
                fga: 7,
            },
            {
                name: 'Svi Mykhailiuk',
                position: 'SG',
                points: 8,
                rebounds: 2,
                assists: 1,
                fgm: 3,
                fga: 8,
            },
            {
                name: 'Payton Pritchard',
                position: 'PG',
                points: 8,
                rebounds: 1,
                assists: 2,
                fgm: 3,
                fga: 6,
            },
        ],
    },
};